modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/TheSmartNoob880/Multiblocked_Extended_Compat/issues"
license="GNU Lesser General Public License v3.0"
[[mods]]
modId="mbdextcompat"
version="1.0"
displayName="Multiblocked Extended Compatability"
displayURL="https://github.com/TheSmartNoob880/Multiblocked_Extended_Compat"
logoFile="mbdextcompat_logo.png"
credits="Thanks to KilaBash and Emperdog for helping me get this mod functional."
authors="TheSmartNoob880, Emperdog"
description='''
An addon mod for Multiblocked that adds additional compatibility with other mods.
'''
[[dependencies.mbdextcompat]]
    modId="forge"
    mandatory=true
    versionRange="[40.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mbdextcompat]]
    modId="multiblocked"
    mandatory=true
    versionRange="[1.0.10,)"
    ordering="AFTER"
    side="BOTH"